import {
  FaBolt,
  FaBrain,
  FaRocket,
  FaStar,
  FaCrown,
  FaCompass,
  FaPuzzlePiece,
  FaTrophy,
  FaClock,
  FaMedal,
  FaGem,
  FaFire,
  FaGlobe,
  FaFlag,
  FaSearch,
  FaFish,
  FaCar,
  FaQuestion,
  FaPalette,
  FaBook,
  FaDice,
  FaMagic,
  FaSkull,
  FaKeyboard,
  FaBrush,
  FaEye,
  // FaMap
} from "react-icons/fa";
import {
  GiPuzzle,
  GiTreasureMap,
  GiBrain as GiBrainIcon,
  GiSpellBook,
  GiCrystalShine,
  GiSpinningWheel,
  GiPodiumWinner,
  GiFishing,
  GiRaceCar,
  GiLetterBomb,
  GiBrain,
  GiJungle,
  GiMagicSwirl,
  GiJigsawPiece,
  GiMoneyStack,
  GiPaintBrush,
  GiPerspectiveDiceSixFacesRandom,
  GiChicken
} from "react-icons/gi";
import { MdQuiz, MdMemory, MdGames, MdNumbers } from "react-icons/md";
import { RiBubbleChartFill } from "react-icons/ri";
import ocean from "../../assets/ocean.jpg";
import millionaire from "../../assets/millionare_hero.png";
import memoryChain from "../../assets/Gemini_Generated_Image_cbujqgcbujqgcbuj.png";
import magicSquare from "../../assets/magic_square.png";
import reverseThinking from "../../assets/reverse_thinking.png";
import baamboozle from "../../assets/Baamboozle_img.png";
import truthImg from "../../assets/truth_detector_img.png";
import jumanjiImg from "../../assets/jumanji_img.png";
import treasureHuntimg from "../../assets/treasure_hunt_img.png";
import mathChickImg from "../../assets/math_chick_img.png"
import { PiDetective } from "react-icons/pi";

const rawGameCards = [
//   {
//   id: "knowledge-adventure",
//   title: "Knowledge Adventure",
//   description: "2 jamoa bilim sarguzashtida xarita bo‘ylab harakat qiladi va savollarga javob berib finishga yetishga harakat qiladi.",
//   mainIcon: GiTreasureMap,
//   icon: FaMap,
//   iconBg: "from-indigo-500 to-purple-500",
//   iconColor: "text-indigo-300",
//   shadowColor: "indigo",
//   available: true,
//   path: "/games/knowledge-adventure",
//   bgPattern: "bg-gradient-to-br from-indigo-600 via-purple-600 to-blue-600",
//   image: "",
//   players: "2 jamoa",
//   level: "3 daraja",
//   levelIcon: FaStar,
//   badge: "NEW",
//   badgeIcon: FaRocket,
//   time: "10-20 min",
//   points: "Team score",
//   category: "Bilim",
//   categoryIcon: FaQuestion,
//   gradient: "from-indigo-400 to-purple-400",
//   borderGlow: "hover:border-indigo-400/50",
// },
  {
    id: "quiz-battle",
    title: "Tezkor Savollar",
    description: "Tezkor savollar, timer va reyting bilan bilim sinovi.",
    mainIcon: MdQuiz,
    icon: FaBolt,
    iconBg: "from-yellow-500 to-orange-500",
    iconColor: "text-yellow-300",
    shadowColor: "yellow",
    available: true,
    path: "/games/quiz-battle",
    bgPattern: "bg-gradient-to-br from-yellow-600 via-orange-600 to-red-600",
    image:
      "https://media.istockphoto.com/id/1336313511/vector/vector-funny-sign-quiz-game-set-of-creative-alphabet-letters-and-numbers.jpg?s=612x612&w=0&k=20&c=V7G9_GmHnJK89C-kt1U1kGDz2uBskO1-Z5fpxph9rX8=",
    players: "1-4 o'yinchi",
    level: "Boshlang'ich",
    levelIcon: FaStar,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "5-10 min",
    points: "1000+",
    category: "Bilim",
    categoryIcon: FaCrown,
    gradient: "from-yellow-400 to-orange-400",
    borderGlow: "hover:border-yellow-400/50",
  },
  {
    id: "memory-rush",
    title: "Xotira Mashqi",
    description: "Xotirani charxlaydigan tezkor kartochkalar o'yini.",
    mainIcon: MdMemory,
    icon: FaBrain,
    iconBg: "from-emerald-500 to-teal-500",
    iconColor: "text-emerald-300",
    shadowColor: "green",
    available: true,
    path: "/games/memory-rush",
    bgPattern: "bg-gradient-to-br from-emerald-600 via-teal-600 to-cyan-600",
    image:
      "https://media.istockphoto.com/id/1434154110/vector/reminder-yellow-note-circled.jpg?s=612x612&w=0&k=20&c=2mfjGFRNi7htNGB47t3fzlfg5mCGLQSfUXMoWBogWL0=",
    players: "2 ta o'yinchi",
    level: "Osson - O'rtacha - Qiyin",
    levelIcon: FaMedal,
    badge: "YANGI",
    badgeIcon: FaClock,
    time: "5-8 min",
    points: "800+",
    category: "Xotira",
    categoryIcon: GiBrainIcon,
    gradient: "from-emerald-400 to-teal-400",
    borderGlow: "hover:border-emerald-400/50",
  },
  {
    id: "treasure-hunt",
    title: "Xazina Izlovchilar",
    description: "Topishmoqlar yechish va xazina topish sarguzashti.",
    mainIcon: GiTreasureMap,
    icon: FaCompass,
    iconBg: "from-amber-500 to-orange-500",
    iconColor: "text-amber-300",
    shadowColor: "amber",
    available: true,
    path: "/games/treasure-hunt",
    bgPattern: "bg-gradient-to-br from-amber-700 via-orange-700 to-yellow-700",
    image: treasureHuntimg,
    players: "1-3 o'yinchi",
    level: "Kreativ",
    levelIcon: GiCrystalShine,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "10-15 min",
    points: "1500+",
    category: "Sarguzasht",
    categoryIcon: FaGem,
    gradient: "from-amber-400 to-orange-400",
    borderGlow: "hover:border-amber-400/50",
  },
  {
    id: "word-battle",
    title: "So'z O'yini",
    description: "So'z topish, harflar bilan o'ynash va lug'at boyitish.",
    mainIcon: RiBubbleChartFill,
    icon: GiSpellBook,
    iconBg: "from-blue-500 to-cyan-500",
    iconColor: "text-blue-300",
    shadowColor: "blue",
    available: true,
    path: "/games/word-battle",
    bgPattern: "bg-gradient-to-br from-blue-600 via-cyan-600 to-sky-600",
    image:
      "https://media.istockphoto.com/id/2186075604/vector/comic-vs-versus-logo-pop-art-style-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=fWIxFgaBpU7jGhTBSxF_5dLwDYywLDzA7VrfKIPDS2Q=",
    players: "2 ta guruh",
    level: "Boshlang'ich",
    levelIcon: FaStar,
    badge: "YANGI",
    badgeIcon: FaFire,
    time: "5-12 min",
    points: "1200+",
    category: "So'z o'yini",
    categoryIcon: FaPuzzlePiece,
    gradient: "from-blue-400 to-cyan-400",
    borderGlow: "hover:border-blue-400/50",
  },
  {
    id: "classic-arcade",
    title: "Mantiq va Tezkorlik",
    description: "Mantiq va tezkorlikni oshiradigan mini challenge'lar.",
    mainIcon: MdGames,
    icon: GiPuzzle,
    iconBg: "from-purple-500 to-pink-500",
    iconColor: "text-purple-300",
    shadowColor: "purple",
    available: true,
    path: "/games/classic-arcade",
    bgPattern: "bg-gradient-to-br from-purple-600 via-pink-600 to-rose-600",
    image:
      "https://media.istockphoto.com/id/1582151789/vector/vector-arcade-premium-alphabet-in-purple-violet-blue-colors-vector-3d-font-text-elements.jpg?s=612x612&w=0&k=20&c=x6f1QrMBy4O6ac6IFTWDG13A9D3vQFK8cIPXGrvA6aA=",
    players: "2 ta guruh",
    level: "Professional",
    levelIcon: FaTrophy,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "5-10 min",
    points: "2000+",
    category: "Mantiq",
    categoryIcon: FaBrain,
    gradient: "from-purple-400 to-pink-400",
    borderGlow: "hover:border-purple-400/50",
  },
  {
    id: "flag-battle",
    title: "Bayroq Topish O'yini",
    description:
      "Dunyo davlatlarining bayroqlarini toping va guruh bo'lib o'ynang.",
    mainIcon: FaFlag,
    icon: FaGlobe,
    iconBg: "from-blue-500 to-cyan-500",
    iconColor: "text-blue-300",
    shadowColor: "blue",
    available: true,
    path: "/games/flag-battle",
    bgPattern: "bg-gradient-to-br from-blue-600 via-cyan-600 to-teal-600",
    players: "2 ta guruh",
    image:
      "https://media.istockphoto.com/id/1030295058/photo/flags-of-different-countries-together-us-flag-in-focus.jpg?s=612x612&w=0&k=20&c=fZ67LXjSvX6LlHflpGF5YpD8bZHNUfzcQW_DvtU3lNQ=",
    level: "Boshlang'ich - Professional",
    levelIcon: FaStar,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "5-8 min",
    points: "1000+",
    category: "Geografiya",
    categoryIcon: FaGlobe,
    gradient: "from-blue-400 to-cyan-400",
    borderGlow: "hover:border-blue-400/50",
  },
  {
    id: "wheel-of-fortune",
    title: "Baraban O'yini",
    description:
      "Baraban aylantiring, tasodifiy o'quvchi tanlang va savollarga javob bering.",
    mainIcon: GiSpinningWheel,
    icon: GiPodiumWinner,
    iconBg: "from-purple-500 to-pink-500",
    iconColor: "text-purple-300",
    shadowColor: "purple",
    available: true,
    path: "/games/wheel-of-fortune",
    bgPattern: "bg-gradient-to-br from-purple-600 via-pink-600 to-rose-600",
    image:
      "https://media.istockphoto.com/id/2177986731/photo/wheel-of-fortune-with-rewards.jpg?s=612x612&w=0&k=20&c=dkony3LqMPl7Mftei-8AkXfoGQgWsOQlqo_7NBeLOT0=",
    players: "2-10 o'quvchi",
    level: "Boshlang'ich - Professional",
    levelIcon: FaStar,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "10-15 min",
    points: "500+",
    category: "Bilim",
    categoryIcon: GiSpinningWheel,
    gradient: "from-purple-400 to-pink-400",
    borderGlow: "hover:border-purple-400/50",
  },
  {
    id: "word-search",
    title: "Yashirin so'zlarni top!",
    description:
      "Harflar ichida yashiringan so'zlarni toping va guruh bo'lib o'ynang.",
    mainIcon: FaSearch,
    icon: FaPuzzlePiece,
    iconBg: "from-emerald-500 to-teal-500",
    iconColor: "text-emerald-300",
    shadowColor: "green",
    available: true,
    path: "/games/word-search",
    bgPattern: "bg-gradient-to-br from-emerald-600 via-teal-600 to-cyan-600",
    image:
      "https://media.istockphoto.com/id/2260590479/vector/vector-easter-village-placemat-spring-holiday-printable-activity-mat-with-maze-crossword.jpg?s=612x612&w=0&k=20&c=YpKwS6BpAuc6dSzcfFuBfTHFyNf9hDxWgwQXHjZOJ7E=",
    players: "2 ta guruh",
    level: "Boshlang'ich - Professional",
    levelIcon: FaStar,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "10-15 min",
    points: "2000+",
    category: "So'z o'yini",
    categoryIcon: FaSearch,
    gradient: "from-emerald-400 to-teal-400",
    borderGlow: "hover:border-emerald-400/50",
  },
  {
    id: "ocean-word-fishing",
    title: "Baliqlar bilan So'z O'yini",
    description:
      "Baliqlar ustidagi harflardan so'zlar yig'ing. Okean sadosi bilan o'ynang va so'zlar toping.",
    mainIcon: FaFish,
    icon: GiFishing,
    iconBg: "from-blue-500 to-cyan-500",
    iconColor: "text-blue-300",
    shadowColor: "blue",
    available: true,
    path: "/games/ocean-word-fishing",
    bgPattern: "bg-gradient-to-br from-blue-600 via-cyan-600 to-teal-600",
    image:ocean,
    players: "1-4 o'yinchi",
    level: "Boshlang'ich - Professional",
    levelIcon: FaStar,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "5-10 min",
    points: "500+",
    category: "So'z o'yini",
    categoryIcon: FaFish,
    gradient: "from-blue-400 to-cyan-400",
    borderGlow: "hover:border-blue-400/50",
  },
  {
    id: "math-race",
    title: "Matematik Poyga",
    description:
      "Ikki o'yinchi tezkor misol ishlash musobaqasida qatnashing. Kim tez va to'g'ri javob bersa, uning mashinasi oldinga yuradi!",
    mainIcon: GiRaceCar,
    icon: FaCar,
    iconBg: "from-yellow-500 to-orange-500",
    iconColor: "text-yellow-300",
    shadowColor: "yellow",
    available: true,
    path: "/games/math-race",
    bgPattern: "bg-gradient-to-br from-yellow-600 via-orange-600 to-red-600",
    image:
      "https://media.istockphoto.com/id/1409623927/vector/formula-racing-sport-car-reach-on-race-circuit-the-finish-line-cartoon-illustration-to-win.jpg?s=612x612&w=0&k=20&c=n5leemMDNJv1g_EFkTJxW9T5XiVQXx0CIA6R2z6Op1U=",
    players: "2 o'yinchi",
    level: "Boshlang'ich - Professional",
    levelIcon: FaStar,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "5-10 min",
    points: "500+",
    category: "Matematika",
    categoryIcon: MdNumbers,
    gradient: "from-yellow-400 to-orange-400",
    borderGlow: "hover:border-yellow-400/50",
  },
{
  id: "baamboozle",
  title: "Baamboozle",
  description: "2-3 jamoa, 16/24 katak. Savollarga javob bering, maxsus kartalar bilan o'yinni qiziqarli qiling. Burn, Swap, Steal va Double sizni kutmoqda!",
  mainIcon: GiPerspectiveDiceSixFacesRandom,
  icon: FaDice,
  iconBg: "from-yellow-500 to-orange-500",
  iconColor: "text-yellow-300",
  shadowColor: "yellow",
  available: true,
  path: "/games/baamboozle",
  bgPattern: "bg-gradient-to-br from-yellow-500 via-orange-500 to-red-500",
  image: baamboozle,
  players: "2-3 jamoa",
  level: "Oson - Qiyin",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaCrown,
  time: "10-25 min",
  points: "100-800 ball",
  category: "Savol-javob",
  categoryIcon: FaDice,
  gradient: "from-yellow-400 to-orange-400",
  borderGlow: "hover:border-yellow-400/50",
},
{
  id: "find-color",
  title: "Farqli Rangni Top!",
  description: "Farqli rangni topish o'yini. 100+ daraja, vaqt bonuslari va global reyting.",
  mainIcon: FaPalette,
  icon: FaPalette,
  iconBg: "from-cyan-500 to-blue-500",
  iconColor: "text-cyan-300",
  shadowColor: "cyan",
  available: true,
  path: "/games/find-color",
  bgPattern: "bg-gradient-to-br from-cyan-600 via-blue-600 to-indigo-600",
  image: "https://media.istockphoto.com/id/2190265535/photo/colorful-paint-cans-forming-a-vibrant-and-inspiring-palette.jpg?s=612x612&w=0&k=20&c=ur_StZRvNfu592Znu3_a0EnzceZZctp11Z4gHk5gsJg=",
  players: "1 o'yinchi",
  level: "Boshlang'ich - Afsonaviy",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaRocket,
  time: "20s",
  points: "310+",
  category: "Xotira",
  categoryIcon: FaPalette,
  gradient: "from-cyan-400 to-blue-400",
  borderGlow: "hover:border-cyan-400/50",
},
{
  id: "bingo",
  title: "Quiz Challenge Bingo",
  description: "O'qituvchi 16 ta katakni tayyorlaydi: quiz, true/false va task topshiriqlari. O'quvchilar navbat bilan kataklarni ochib, savollarga javob beradi va ball to'playdi.",
  mainIcon: GiJigsawPiece,
  icon: FaBrain,
  iconBg: "from-indigo-500 to-purple-500",
  iconColor: "text-indigo-300",
  shadowColor: "indigo",
  available: true,
  path: "/games/bingo",
  bgPattern: "bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500",
  image: "https://media.istockphoto.com/id/495611580/vector/bingo-or-lottery-retro-game-illustration-with-balls-and-cards.jpg?s=612x612&w=0&k=20&c=lyncdZNnRRPcClMJuAGV10F-a-6iTutSKilAuxaHKu4=",
  players: "2-30 o'quvchi",
  level: "3 xil qiyinlik",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaRocket,
  time: "15-25 min",
  points: "500+",
  category: "Bilim",
  categoryIcon: FaQuestion,
  gradient: "from-indigo-400 to-purple-400",
  borderGlow: "hover:border-indigo-400/50",
},
{
  id: "sozlar-zanjiri",
  title: "So'zlar Zanjiri",
  description: "Har bir so'z oldingi so'zning oxirgi harfi bilan boshlanadi. 2-6 o'quvchi navbat bilan so'z topadi. Eng ko'p so'z topgan g'olib!",
  mainIcon: GiLetterBomb,
  icon: FaBook,
  iconBg: "from-purple-500 to-pink-500",
  iconColor: "text-purple-300",
  shadowColor: "purple",
  available: true,
  path: "/games/word-chain",
  bgPattern: "bg-gradient-to-br from-purple-500 via-pink-500 to-rose-500",
  image:  "https://media.istockphoto.com/id/1503421139/photo/multi-colored-alphabet-letters-and-magnifying-glass-on-the-yellow-background.jpg?s=612x612&w=0&k=20&c=losfLdOo6_oPE5GQmJGdfzC1haNnVSIGiAeOs7VCGDo=",
  players: "2-6 o'quvchi",
  level: "Boshlang'ich - Professional",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaRocket,
  time: "30s",
  points: "100+",
  category: "So'z o'yini",
  categoryIcon: FaBook,
  gradient: "from-purple-400 to-pink-400",
  borderGlow: "hover:border-purple-400/50",
},
{
  id: "memory-chain",
  title: "Memory Chain Arena",
  description: "2 jamoa navbat bilan zanjirni eslab qoladi va tezda takrorlaydi. Xotira va tezkorlik o'yini.",
  mainIcon: GiBrain,
  icon: FaBrain,
  iconBg: "from-cyan-500 to-blue-500",
  iconColor: "text-cyan-300",
  shadowColor: "cyan",
  available: true,
  path: "/games/memory-chain",
  bgPattern: "bg-gradient-to-br from-cyan-500 via-blue-500 to-indigo-500",
  image: memoryChain,
  players: "2 jamoa",
  level: "Oson - Qiyin",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaRocket,
  time: "30s",
  points: "1000+",
  category: "Xotira",
  categoryIcon: FaBrain,
  gradient: "from-cyan-400 to-blue-400",
  borderGlow: "hover:border-cyan-400/50",
},
{
  id: "jumanji",
  title: "Jumanji",
  description: "O‘z dunyosidan chiqish yo‘lini izlayotganlar uchun o‘yin. Zarni tashlang, savollarga javob bering va marraga birinchi bo‘lib yetib boring!",
  mainIcon: GiJungle,
  icon: FaDice,
  iconBg: "from-amber-800 to-amber-600",
  iconColor: "text-amber-300",
  shadowColor: "amber",
  available: true,
  path: "/games/jumanji",
  bgPattern: "bg-gradient-to-br from-amber-900 via-amber-800 to-amber-700",
  image: jumanjiImg,
  players: "2 JAMOA",
  level: "BARCHA DARAJALAR",
  levelIcon: FaStar,
  badge: "RETRO",
  badgeIcon: FaCrown,
  time: "10-15 DAQIQA",
  points: "500+",
  category: "Sarguzasht",
  categoryIcon: GiJungle,
  gradient: "from-amber-600 to-amber-400",
  borderGlow: "hover:border-amber-400/50",
},
{
  id: "mini-puzzle",
  title: "Rasmni Yig'",
  description: "2 jamoa musobaqalashadi. Rasm bo'laklarini yig'ing va birinchi bo'lib to'liq rasmni hosil qiling!",
  mainIcon: GiPuzzle,
  icon: FaPuzzlePiece,
  iconBg: "from-pink-500 to-rose-500",
  iconColor: "text-pink-300",
  shadowColor: "pink",
  available: true,
  path: "/games/mini-puzzle",
  bgPattern: "bg-gradient-to-br from-pink-500 via-rose-500 to-pink-500",
  image: "https://media.istockphoto.com/id/2249204910/photo/jigsaw-puzzle-pieces-colorful-background-with-small-puzzle-pieces-messy-some-colored-pieces.jpg?s=612x612&w=0&k=20&c=r43dtrUR7kvYbZHLZa6OVcbETVnFLOVhayJWwMwLUUc=",
   players: "2 jamoa",
  level: "Oson - Qiyin",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaRocket,
  time: "5-10 min",
  points: "500+",
  category: "Puzzle",
  categoryIcon: FaPuzzlePiece,
  gradient: "from-pink-400 to-rose-400",
  borderGlow: "hover:border-pink-400/50",
},
{
  id: "magic-square",
  title: "Sehrli Kvadrat",
  description: "3x3 rangli sudoku. Har bir qator va ustunda barcha 3 rang bo'lishi kerak. Jamoalar navbat bilan o'ynaydi!",
  mainIcon: GiMagicSwirl,
  icon: FaMagic,
  iconBg: "from-purple-500 to-pink-500",
  iconColor: "text-purple-300",
  shadowColor: "purple",
  available: true,
  path: "/games/magic-square",
  bgPattern: "bg-gradient-to-br from-purple-500 via-pink-500 to-purple-500",
  image: magicSquare,
  players: "2 jamoa",
  level: "Oson - O'rtacha",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaRocket,
  time: "5-8 min",
  points: "300+",
  category: "Mantiq",
  categoryIcon: GiMagicSwirl,
  gradient: "from-purple-400 to-pink-400",
  borderGlow: "hover:border-purple-400/50",
},
{
  id: "reverse-thinking",
  title: "Teskari Fikr",
  description: "Mantiqiy tuzoqlar va chalg'ituvchi savollar orqali fikrlash qobiliyatingizni sinang. 2 jamoa musobaqalashadi!",
  mainIcon: GiBrain,
  icon: FaBrain,
  iconBg: "from-green-500 to-emerald-500",
  iconColor: "text-green-300",
  shadowColor: "green",
  available: true,
  path: "/games/reverse-thinking",
  bgPattern: "bg-gradient-to-br from-green-500 via-emerald-500 to-green-500",
  image: reverseThinking,
  players: "2 jamoa",
  level: "1-4 daraja",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaRocket,
  time: "10-15 min",
  points: "500+",
  category: "Mantiq",
  categoryIcon: FaBrain,
  gradient: "from-green-400 to-emerald-400",
  borderGlow: "hover:border-green-400/50",
},
{
  id: "hangman",
  title: "2 Jamoali Hangman",
  description: "Bir jamoa so'z yashiradi, ikkinchi jamoa harflar tanlab so'zni topishga harakat qiladi. 6 xato - o'yin tugaydi!",
  mainIcon: GiLetterBomb,
  icon: FaSkull,
  iconBg: "from-amber-500 to-red-500",
  iconColor: "text-amber-300",
  shadowColor: "amber",
  available: true,
  path: "/games/hangman",
  bgPattern: "bg-gradient-to-br from-amber-500 via-red-500 to-rose-500",
  image: "https://media.istockphoto.com/id/1367166428/photo/bankrupt-says-the-solution-to-a-traditional-word-game-of-hangman.jpg?s=612x612&w=0&k=20&c=Ddquk--5soZs7KtdY4vudhul8BMuNFu-0gBwU1_gE4w=", 
  players: "2 jamoa",
  level: "Oson - Qiyin",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaRocket,
  time: "10-20 min",
  points: "Raund +1",
  category: "So'z o'yini",
  categoryIcon: FaKeyboard,
  gradient: "from-amber-400 to-red-400",
  borderGlow: "hover:border-amber-400/50",
},
{
  id: "millionaire",
  title: "Kim millioner bo'lishni xohlaydi?",
  description: "3-5 o'yinchi navbat bilan savollarga javob beradi. 15 pog'onali pul ro'yxati, 4 qiyinlik darajasi va safe level tizimi.",
  mainIcon: GiMoneyStack,
  icon: FaCrown,
  iconBg: "from-yellow-500 to-amber-500",
  iconColor: "text-yellow-300",
  shadowColor: "yellow",
  available: true,
  path: "/games/millionaire",
  bgPattern: "bg-gradient-to-br from-yellow-600 via-amber-600 to-orange-600",
  image: millionaire, 
  players: "1 jamoa", 
  level: "4 daraja",
  levelIcon: FaStar,
  badge: "PREMIUM",
  badgeIcon: FaCrown,
  time: "15-30 min",
  points: "15 000 000 so'm",
  category: "Bilim",
  categoryIcon: FaQuestion,
  gradient: "from-yellow-400 to-amber-400",
  borderGlow: "hover:border-yellow-400/50",
},
{
  id: "pictionary",
  title: "Chiz va Top!",
  description: "2 jamoa. Bir jamoa chizadi, ikkinchisi so'zni topadi. Har bir to'g'ri javob uchun 1 ball. Raund oshgani sari so'zlar qiyinlashadi!",
  mainIcon: GiPaintBrush,
  icon: FaBrush,
  iconBg: "from-indigo-500 to-purple-500",
  iconColor: "text-indigo-300",
  shadowColor: "indigo",
  available: false,
  path: "/games/pictionary",
  bgPattern: "bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500",
  image: "https://media.istockphoto.com/id/2225108078/vector/hand-drawn-doodle-rock-punk-pop-music-festival-funky-background-karaoke-bachelorette-girly.jpg?s=612x612&w=0&k=20&c=fQGF0A9QZClxs8hFGG6RbtSsxqfWIy0X2NiB31G1aUU=",
  players: "2 jamoa",
  level: "3 daraja",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaCrown,
  time: "30-90 s",
  points: "1 ball / raund",
  category: "Chizish",
  categoryIcon: FaBrush,
  gradient: "from-indigo-400 to-purple-400",
  borderGlow: "hover:border-indigo-400/50",
},
{
  id: "truth-detector",
  title: "Rostmi yoki yolg‘on?",
  description: "3-5 o'yinchi. Har raundda 3 ta claim beriladi. 2 tasi TRUE, 1 tasi FAKE. FAKE'ni topgan o'yinchi +1 ball oladi.",
  mainIcon: PiDetective,
  icon: FaEye,
  iconBg: "from-indigo-500 to-purple-500",
  iconColor: "text-indigo-300",
  shadowColor: "indigo",
  available: true,
  path: "/games/truth-detector",
  bgPattern: "bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500",
  image: truthImg,
  players: "3-5 o'yinchi",
  level: "3 daraja",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaCrown,
  time: "10-20 min",
  points: "1 ball / FAKE",
  category: "Mantiq",
  categoryIcon: GiBrain,
  gradient: "from-indigo-400 to-purple-400",
  borderGlow: "hover:border-indigo-400/50",
},
{
  id: "math-chick",
  title: "Math Chick Game",
  description: "Jo'jacha bilan matematik sarguzasht! Tangalarni yig'ing, misollarni yeching va eng yuqori ballga erishing.",
  mainIcon: GiChicken,
  icon: FaBrain,
  iconBg: "from-blue-500 to-violet-600",
  iconColor: "text-yellow-300",
  shadowColor: "blue",
  available: true,
  path: "/games/math-chick",
  bgPattern: "bg-gradient-to-br from-[#243a86] via-[#402a93] to-[#1a245f]",
  image: mathChickImg,
  players: "2 o'yinchi",
  level: "Osson - O'rtacha - Qiyin",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaCrown,
  time: "5-10 min",
  points: "1000+",
  category: "Matematika",
  categoryIcon: FaBrain,
  gradient: "from-yellow-300 to-amber-400",
  borderGlow: "hover:border-violet-400/50",
}
 ];

const curatedGameOrder = [
  "knowledge-adventure",
  "millionaire",
  "jumanji",
  "classic-arcade",
  "math-race",
  "math-chick",
  "treasure-hunt",
  "quiz-battle",
  "baamboozle",
  "pictionary",
  "truth-detector",
  "word-battle",
  "word-search",
  "bingo",
  "flag-battle",
  "memory-rush",
  "memory-chain",
  "wheel-of-fortune",
  "ocean-word-fishing",
  "magic-square",
  "reverse-thinking",
  "mini-puzzle",
  "word-chain",
  "hangman",
  "find-color",
] as const;

const curatedGameOrderMap = new Map(
  curatedGameOrder.map((id, index) => [id, index]),
);

export const gameCards = [...rawGameCards].sort((a, b) => {
  const aIndex = curatedGameOrderMap.get(a.id as typeof curatedGameOrder[number]) ?? Number.MAX_SAFE_INTEGER;
  const bIndex = curatedGameOrderMap.get(b.id as typeof curatedGameOrder[number]) ?? Number.MAX_SAFE_INTEGER;
  return aIndex - bIndex;
});

