import {
  FaBolt,
  FaBrain,
  FaRocket,
  FaStar,
  FaCrown,
  FaCompass,
  FaPuzzlePiece,
  FaTrophy,
  FaClock,
  FaMedal,
  FaGem,
  FaFire,
  FaGlobe,
  FaFlag,
  FaSearch,
  FaFish,
} from "react-icons/fa";
import {
  GiPuzzle,
  GiTreasureMap,
  GiBrain as GiBrainIcon,
  GiSpellBook,
  GiCrystalShine,
  GiSpinningWheel,
  GiPodiumWinner,
  GiFishing,
} from "react-icons/gi";
import { MdQuiz, MdMemory, MdGames } from "react-icons/md";
import { RiBubbleChartFill } from "react-icons/ri";

export const gameCards = [
  {
    id: "quiz-battle",
    title: "Quiz Battle",
    description: "Tezkor savollar, timer va reyting bilan bilim sinovi.",
    mainIcon: MdQuiz,
    icon: FaBolt,
    iconBg: "from-yellow-500 to-orange-500",
    iconColor: "text-yellow-300",
    shadowColor: "yellow",
    available: true,
    path: "/games/quiz-battle",
    bgPattern: "bg-gradient-to-br from-yellow-600 via-orange-600 to-red-600",
    image:
      "https://media.istockphoto.com/id/1336313511/vector/vector-funny-sign-quiz-game-set-of-creative-alphabet-letters-and-numbers.jpg?s=612x612&w=0&k=20&c=V7G9_GmHnJK89C-kt1U1kGDz2uBskO1-Z5fpxph9rX8=",
    players: "1-4 o'yinchi",
    level: "Boshlang'ich",
    levelIcon: FaStar,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "5-10 min",
    points: "1000+",
    category: "Bilim",
    categoryIcon: FaCrown,
    gradient: "from-yellow-400 to-orange-400",
    borderGlow: "hover:border-yellow-400/50",
  },
  {
    id: "memory-rush",
    title: "Memory Rush",
    description: "Xotirani charxlaydigan tezkor kartochkalar o'yini.",
    mainIcon: MdMemory,
    icon: FaBrain,
    iconBg: "from-emerald-500 to-teal-500",
    iconColor: "text-emerald-300",
    shadowColor: "green",
    available: true,
    path: "/games/memory-rush",
    bgPattern: "bg-gradient-to-br from-emerald-600 via-teal-600 to-cyan-600",
    image:
      "https://media.istockphoto.com/id/1434154110/vector/reminder-yellow-note-circled.jpg?s=612x612&w=0&k=20&c=2mfjGFRNi7htNGB47t3fzlfg5mCGLQSfUXMoWBogWL0=",
    players: "2 ta o'yinchi",
    level: "Osson - O'rtacha - Qiyin",
    levelIcon: FaMedal,
    badge: "YANGI",
    badgeIcon: FaClock,
    time: "5-8 min",
    points: "800+",
    category: "Xotira",
    categoryIcon: GiBrainIcon,
    gradient: "from-emerald-400 to-teal-400",
    borderGlow: "hover:border-emerald-400/50",
  },
  {
    id: "treasure-hunt",
    title: "Treasure Hunt",
    description: "Topishmoqlar yechish va xazina topish sarguzashti.",
    mainIcon: GiTreasureMap,
    icon: FaCompass,
    iconBg: "from-amber-500 to-orange-500",
    iconColor: "text-amber-300",
    shadowColor: "amber",
    available: true,
    path: "/games/treasure-hunt",
    bgPattern: "bg-gradient-to-br from-amber-700 via-orange-700 to-yellow-700",
    image:
      "https://media.istockphoto.com/id/1341261769/photo/treasure-map.jpg?s=612x612&w=0&k=20&c=JnZD0II52_tMPZ-U_emWhZ9GfRu92SdWsZFFy8ohKw8=",
    players: "1-3 o'yinchi",
    level: "Kreativ",
    levelIcon: GiCrystalShine,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "10-15 min",
    points: "1500+",
    category: "Sarguzasht",
    categoryIcon: FaGem,
    gradient: "from-amber-400 to-orange-400",
    borderGlow: "hover:border-amber-400/50",
  },
  {
    id: "word-battle",
    title: "Word Battle",
    description: "So'z topish, harflar bilan o'ynash va lug'at boyitish.",
    mainIcon: RiBubbleChartFill,
    icon: GiSpellBook,
    iconBg: "from-blue-500 to-cyan-500",
    iconColor: "text-blue-300",
    shadowColor: "blue",
    available: true,
    path: "/games/word-battle",
    bgPattern: "bg-gradient-to-br from-blue-600 via-cyan-600 to-sky-600",
    image:
      "https://media.istockphoto.com/id/2186075604/vector/comic-vs-versus-logo-pop-art-style-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=fWIxFgaBpU7jGhTBSxF_5dLwDYywLDzA7VrfKIPDS2Q=",
    players: "2 ta guruh",
    level: "Boshlang'ich",
    levelIcon: FaStar,
    badge: "YANGI",
    badgeIcon: FaFire,
    time: "5-12 min",
    points: "1200+",
    category: "So'z",
    categoryIcon: FaPuzzlePiece,
    gradient: "from-blue-400 to-cyan-400",
    borderGlow: "hover:border-blue-400/50",
  },
  {
    id: "classic-arcade",
    title: "Classic Arcade",
    description: "Mantiq va tezkorlikni oshiradigan mini challenge'lar.",
    mainIcon: MdGames,
    icon: GiPuzzle,
    iconBg: "from-purple-500 to-pink-500",
    iconColor: "text-purple-300",
    shadowColor: "purple",
    available: true,
    path: "/games/classic-arcade",
    bgPattern: "bg-gradient-to-br from-purple-600 via-pink-600 to-rose-600",
    image:
      "https://media.istockphoto.com/id/1582151789/vector/vector-arcade-premium-alphabet-in-purple-violet-blue-colors-vector-3d-font-text-elements.jpg?s=612x612&w=0&k=20&c=x6f1QrMBy4O6ac6IFTWDG13A9D3vQFK8cIPXGrvA6aA=",
    players: "2 ta guruh",
    level: "Professional",
    levelIcon: FaTrophy,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "5-10 min",
    points: "2000+",
    category: "Mantiq",
    categoryIcon: FaBrain,
    gradient: "from-purple-400 to-pink-400",
    borderGlow: "hover:border-purple-400/50",
  },
  {
    id: "flag-battle",
    title: "Flag Battle",
    description:
      "Dunyo davlatlarining bayroqlarini toping va guruh bo'lib o'ynang.",
    mainIcon: FaFlag,
    icon: FaGlobe,
    iconBg: "from-blue-500 to-cyan-500",
    iconColor: "text-blue-300",
    shadowColor: "blue",
    available: true,
    path: "/games/flag-battle",
    bgPattern: "bg-gradient-to-br from-blue-600 via-cyan-600 to-teal-600",
    players: "2 ta guruh",
    image:
      "https://media.istockphoto.com/id/1030295058/photo/flags-of-different-countries-together-us-flag-in-focus.jpg?s=612x612&w=0&k=20&c=fZ67LXjSvX6LlHflpGF5YpD8bZHNUfzcQW_DvtU3lNQ=",
    level: "Boshlang'ich - Professional",
    levelIcon: FaStar,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "5-8 min",
    points: "1000+",
    category: "Geografiya",
    categoryIcon: FaGlobe,
    gradient: "from-blue-400 to-cyan-400",
    borderGlow: "hover:border-blue-400/50",
  },
  {
    id: "wheel-of-fortune",
    title: "Wheel of Fortune",
    description:
      "Baraban aylantiring, tasodifiy o'quvchi tanlang va savollarga javob bering.",
    mainIcon: GiSpinningWheel,
    icon: GiPodiumWinner,
    iconBg: "from-purple-500 to-pink-500",
    iconColor: "text-purple-300",
    shadowColor: "purple",
    available: true,
    path: "/games/wheel-of-fortune",
    bgPattern: "bg-gradient-to-br from-purple-600 via-pink-600 to-rose-600",
    image:
      "https://media.istockphoto.com/id/2177986731/photo/wheel-of-fortune-with-rewards.jpg?s=612x612&w=0&k=20&c=dkony3LqMPl7Mftei-8AkXfoGQgWsOQlqo_7NBeLOT0=",
    players: "2-10 o'quvchi",
    level: "Boshlang'ich - Professional",
    levelIcon: FaStar,
    badge: "YANGI",
    badgeIcon: FaRocket,
    time: "10-15 min",
    points: "500+",
    category: "Bilim",
    categoryIcon: GiSpinningWheel,
    gradient: "from-purple-400 to-pink-400",
    borderGlow: "hover:border-purple-400/50",
  },
  {
  id: "word-search",
  title: "Word Search",
  description: "Harflar ichida yashiringan so'zlarni toping va guruh bo'lib o'ynang.",
  mainIcon: FaSearch,
  icon: FaPuzzlePiece,
  iconBg: "from-emerald-500 to-teal-500",
  iconColor: "text-emerald-300",
  shadowColor: "green",
  available: true,
  path: "/games/word-search",
  bgPattern: "bg-gradient-to-br from-emerald-600 via-teal-600 to-cyan-600",
  image: "https://media.istockphoto.com/id/2260590479/vector/vector-easter-village-placemat-spring-holiday-printable-activity-mat-with-maze-crossword.jpg?s=612x612&w=0&k=20&c=YpKwS6BpAuc6dSzcfFuBfTHFyNf9hDxWgwQXHjZOJ7E=",
  players: "2 ta guruh",
  level: "Boshlang'ich - Professional",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaRocket,
  time: "10-15 min",
  points: "2000+",
  category: "So'z o'yini",
  categoryIcon: FaSearch,
  gradient: "from-emerald-400 to-teal-400",
  borderGlow: "hover:border-emerald-400/50",
},
{
  id: "ocean-word-fishing",
  title: "Ocean Word Fishing",
  description: "Baliqlar ustidagi harflardan so'zlar yig'ing. Okean sadosi bilan o'ynang va so'zlar toping.",
  mainIcon: FaFish,
  icon: GiFishing,
  iconBg: "from-blue-500 to-cyan-500",
  iconColor: "text-blue-300",
  shadowColor: "blue",
  available: true,
  path: "/games/ocean-word-fishing",
  bgPattern: "bg-gradient-to-br from-blue-600 via-cyan-600 to-teal-600",
  image: "https://media.istockphoto.com/id/537816526/vector/underwater-world.jpg?s=612x612&w=0&k=20&c=U_1QpgfCsqkNFdbiLqFs6C-RyC5d2Eyfl5Kf8_YBgT0=",
  players: "1-4 o'yinchi",
  level: "Boshlang'ich - Professional",
  levelIcon: FaStar,
  badge: "YANGI",
  badgeIcon: FaRocket,
  time: "5-10 min",
  points: "500+",
  category: "So'z o'yini",
  categoryIcon: FaFish,
  gradient: "from-blue-400 to-cyan-400",
  borderGlow: "hover:border-blue-400/50",
},
];
