import type { Question } from "../types";

export const DEFAULT_QUESTIONS: Question[] = [
  {
    id: "1",
    subject: "Matematika",
    question: "12 * 8 nechiga teng?",
    options: ["96", "84", "108", "88"],
    correctAnswer: "96",
    difficulty: "easy",
    timeLimit: 30,
  },
  {
    id: "2",
    subject: "Matematika",
    question: "3/4 ni foizda ifodalang.",
    options: ["60%", "70%", "75%", "80%"],
    correctAnswer: "75%",
    difficulty: "easy",
    timeLimit: 30,
  },
  {
    id: "3",
    subject: "Ingliz tili",
    question: "'Go' fe'lining Past Simple shakli qaysi?",
    options: ["goed", "went", "gone", "goes"],
    correctAnswer: "went",
    difficulty: "easy",
    timeLimit: 30,
  },
  {
    id: "4",
    subject: "Ingliz tili",
    question: "I ___ to school every day.",
    options: ["go", "goes", "went", "gone"],
    correctAnswer: "go",
    difficulty: "easy",
    timeLimit: 30,
  },
  {
    id: "5",
    subject: "Tarix",
    question: "Amir Temur qaysi asrda yashagan?",
    options: ["XII", "XIV", "XVI", "XVIII"],
    correctAnswer: "XIV",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "6",
    subject: "Tarix",
    question: "O'zbekiston mustaqilligi qachon e'lon qilingan?",
    options: ["1990", "1991", "1992", "1993"],
    correctAnswer: "1991",
    difficulty: "easy",
    timeLimit: 30,
  },
  {
    id: "7",
    subject: "Geografiya",
    question: "Yer yuzidagi eng uzun daryo qaysi?",
    options: ["Nil", "Amazonka", "Yanszi", "Missisipi"],
    correctAnswer: "Nil",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "8",
    subject: "Geografiya",
    question: "O'zbekiston poytaxti qaysi shahar?",
    options: ["Samarqand", "Buxoro", "Toshkent", "Nukus"],
    correctAnswer: "Toshkent",
    difficulty: "easy",
    timeLimit: 25,
  },
  {
    id: "9",
    subject: "Biologiya",
    question: "Inson tanasidagi eng katta organ qaysi?",
    options: ["Yurak", "Jigar", "Teri", "O'pka"],
    correctAnswer: "Teri",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "10",
    subject: "Biologiya",
    question: "Fotosintez asosan qaysi organellada kechadi?",
    options: ["Mitoxondriya", "Xloroplast", "Yadro", "Ribosoma"],
    correctAnswer: "Xloroplast",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "11",
    subject: "Ona tili",
    question: "Sinonim so'zlar nimani bildiradi?",
    options: ["Qarama-qarshi ma'no", "Bir xil yoki yaqin ma'no", "Faqat otlar", "Faqat fe'llar"],
    correctAnswer: "Bir xil yoki yaqin ma'no",
    difficulty: "easy",
    timeLimit: 30,
  },
  {
    id: "12",
    subject: "Ona tili",
    question: "'Kitoblar' so'zida nechta bo'g'in bor?",
    options: ["2", "3", "4", "5"],
    correctAnswer: "3",
    difficulty: "easy",
    timeLimit: 25,
  },
  {
    id: "13",
    subject: "Matematika",
    question: "(15 + 5) / 4 nechiga teng?",
    options: ["4", "5", "6", "7"],
    correctAnswer: "5",
    difficulty: "easy",
    timeLimit: 30,
  },
  {
    id: "14",
    subject: "Matematika",
    question: "Kvadratning 1 tomoni 9 sm bo'lsa, perimetri nechiga teng?",
    options: ["18", "27", "36", "45"],
    correctAnswer: "36",
    difficulty: "easy",
    timeLimit: 30,
  },
  {
    id: "15",
    subject: "Ingliz tili",
    question: "'Beautiful' so'zining sinonimini toping.",
    options: ["ugly", "pretty", "small", "short"],
    correctAnswer: "pretty",
    difficulty: "easy",
    timeLimit: 30,
  },
  {
    id: "16",
    subject: "Tarix",
    question: "Buyuk Ipak yo'li asosan nima uchun xizmat qilgan?",
    options: ["Faqat urush", "Savdo va madaniy almashinuv", "Faqat ko'chish", "Faqat diniy marosim"],
    correctAnswer: "Savdo va madaniy almashinuv",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "17",
    subject: "Geografiya",
    question: "Qaysi okean eng katta?",
    options: ["Hind", "Atlantika", "Tinch", "Shimoliy Muz"],
    correctAnswer: "Tinch",
    difficulty: "easy",
    timeLimit: 30,
  },
  {
    id: "18",
    subject: "Biologiya",
    question: "Qon tarkibida kislorod tashuvchi hujayralar qaysi?",
    options: ["Leykotsit", "Trombotsit", "Eritrotsit", "Neyron"],
    correctAnswer: "Eritrotsit",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "19",
    subject: "Ona tili",
    question: "Gapning asosiy bo'laklari qaysilar?",
    options: ["Ega va kesim", "Aniqlovchi va to'ldiruvchi", "Hol va aniqlovchi", "Faqat ega"],
    correctAnswer: "Ega va kesim",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "20",
    subject: "Informatika",
    question: "Kompyuterning vaqtinchalik xotirasi qaysi?",
    options: ["SSD", "HDD", "RAM", "ROM"],
    correctAnswer: "RAM",
    difficulty: "easy",
    timeLimit: 30,
  },
  {
    id: "21",
    subject: "Informatika",
    question: "HTML nimaning qisqartmasi?",
    options: ["Hyper Text Markup Language", "High Transfer Machine Language", "Home Tool Mark Language", "Hyper Tool Markdown Language"],
    correctAnswer: "Hyper Text Markup Language",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "22",
    subject: "Matematika",
    question: "7 ning kvadrati nechiga teng?",
    options: ["14", "49", "56", "64"],
    correctAnswer: "49",
    difficulty: "easy",
    timeLimit: 25,
  },
  {
    id: "23",
    subject: "Geografiya",
    question: "Qaysi qit'a eng kichik?",
    options: ["Yevropa", "Avstraliya", "Antarktida", "Janubiy Amerika"],
    correctAnswer: "Avstraliya",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "24",
    subject: "Tarix",
    question: "\"Temur tuzuklari\" asari kimga tegishli?",
    options: ["Alisher Navoiy", "Amir Temur", "Bobur", "Ulug'bek"],
    correctAnswer: "Amir Temur",
    difficulty: "medium",
    timeLimit: 35,
  },
];
