import type { Question } from "./ReverseThinking";

export const MORE_QUESTIONS: Question[] = [
  // Level 1 - Oddiy chalg'ituvchi
  {
    id: "16",
    level: 1,
    question: "Qaysi narsa qanchalik ko'p olsa, shunchalik yengillashadi?",
    options: ["Sumka", "Yuk", "Teshik", "Pul"],
    correctAnswer: "Teshik",
    explanation: "Teshik qancha ko'p olsa (kattalashsa), shuncha 'yengil' bo'lib ketadi 😄",
  },
  {
    id: "17",
    level: 1,
    question: "Qaysi soat kuniga ikki marta to'g'ri vaqtni ko'rsatadi?",
    options: ["Elektron soat", "Yangi soat", "To'xtab qolgan soat", "Qum soat"],
    correctAnswer: "To'xtab qolgan soat",
    explanation: "To'xtab qolgan soat 12 soatda 2 marta to'g'ri keladi 😊",
  },
  {
    id: "18",
    level: 1,
    question: "Qaysi narsani ko'proq sindirsang, kattalashadi?",
    options: ["Oyna", "Shisha", "Tuxum", "Sir"],
    correctAnswer: "Sir",
    explanation: "Sirni ko'p ochsang, u 'kattalashib' ketadi 😄",
  },
  {
    id: "19",
    level: 1,
    question: "Qaysi narsa doim oldinga yuradi, lekin hech qayerga bormaydi?",
    options: ["Soat", "Mashina", "Odam", "Daryo"],
    correctAnswer: "Soat",
    explanation: "Soat strelkasi oldinga yuradi, lekin joyidan qimirlmaydi 😊",
  },

  // Level 2 - Mantiqiy savollar
  {
    id: "20",
    level: 2,
    question: "2 ta ota va 2 ta o'g'il 3 ta olmani teng bo'lib yedi. Har biri nechta olma yedi?",
    options: ["1 ta", "1.5 ta", "2 ta", "0.5 ta"],
    correctAnswer: "1 ta",
    explanation: "Ular aslida 3 kishi: bobo, ota, o'g'il. 3 olma → har biri 1 tadan 😊",
  },
  {
    id: "21",
    level: 2,
    question: "Agar siz 1 ta gugurtni 1 daqiqada yoqsangiz, 10 ta gugurtni necha daqiqada yoqasiz?",
    options: ["10 daqiqa", "1 daqiqa", "0 daqiqa", "Bilmayman"],
    correctAnswer: "1 daqiqa",
    explanation: "Hammasini bir vaqtda yoqsangiz 1 daqiqa ketadi 😄",
  },
  {
    id: "22",
    level: 2,
    question: "Qaysi savolga siz doim 'ha' deb javob berasiz?",
    options: ["Siz uxlayapsizmi?", "Siz tirikmisiz?", "Siz hozir javob beryapsizmi?", "Siz robotmisiz?"],
    correctAnswer: "Siz hozir javob beryapsizmi?",
    explanation: "Savolga javob berayotgan bo'lsangiz, demak javob beryapsiz 😊",
  },
  {
    id: "23",
    level: 2,
    question: "Bir xonada 3 ta chiroq va tashqarida 3 ta tugma bor. Siz xonaga faqat 1 marta kira olasiz. Qaysi tugma qaysi chiroqqa tegishli ekanini qanday bilasiz?",
    options: ["Barchasini yoqib ko'raman", "Birini yoqib, birini ushlab ko'raman", "1-tugmani yoqib kutaman, o'chirib 2-tugmani yoqaman, keyin kiraman", "Bilmayman"],
    correctAnswer: "1-tugmani yoqib kutaman, o'chirib 2-tugmani yoqaman, keyin kiraman",
    explanation: "1-chi issiq (lekin o'chiq), 2-chi yoqilgan, 3-chi o'chiq va sovuq 😊",
  },
  {
    id: "24",
    level: 2,
    question: "Sizda 3 litrli va 5 litrli idish bor. Qanday qilib aynan 4 litr suv o'lchaysiz?",
    options: ["Imkonsiz", "5 ni to'ldirib 3 ga quyib, 5 da 2 qoldiraman; 3 ni bo'shatib 2 ni unga quyaman; 5 ni to'ldirib 3 to'lgunga qadar quyaman", "3 ni to'ldirib 5 ga quyaman", "Faqat 5 litr o'lchayman"],
    correctAnswer: "5 ni to'ldirib 3 ga quyib, 5 da 2 qoldiraman; 3 ni bo'shatib 2 ni unga quyaman; 5 ni to'ldirib 3 to'lgunga qadar quyaman",
    explanation: "Klassik mantiqiy masala: oxirida 5 idishda 4 litr qoladi 😊",
  },

  // Level 3 - Juda tricky savollar
  {
    id: "25",
    level: 3,
    question: "Sizda bitta non bor. Uni 3 marta kesib 8 ta teng bo'lak qilish mumkinmi?",
    options: ["Ha", "Yo'q", "Faqat pichoq o'tkir bo'lsa", "Faqat katta non bo'lsa"],
    correctAnswer: "Ha",
    explanation: "1-kesish 2 bo'lak, 2-kesish 4 bo'lak, 3-kesish 8 bo'lak (ustma-ust qilib kesilsa) 😊",
  },
  {
    id: "26",
    level: 3,
    question: "Bir odam 1-qavatdan 10-qavatga lift bilan chiqishni yoqtiradi. Lekin 10-qavatdan 1-qavatga faqat 7-qavatgacha tushadi, keyin zinadan tushadi. Nega?",
    options: ["Lift buzilgan", "U charchaydi", "U past bo'yli", "U zinani yoqtiradi"],
    correctAnswer: "U past bo'yli",
    explanation: "U faqat 7-qavat tugmasigacha yetadi 😄",
  },
  {
    id: "27",
    level: 3,
    question: "Qaysi so'zning boshini olib tashlasangiz ham, oxirini olib tashlasangiz ham bir xil qoladi?",
    options: ["Ana", "Uu", "Non", "Qalam"],
    correctAnswer: "Ana",
    explanation: "'Ana' dan boshini olsangiz 'na', oxirini olsangiz ham 'an' — bu savol hazil/tricky 😄 (xohlasang almashtirib beraman)",
  },
  {
    id: "28",
    level: 3,
    question: "Sizda 12 ta shar bor, ulardan 1 tasi boshqalaridan og'irroq. Tarozida 3 marta tortib og'ir sharni qanday topasiz?",
    options: ["Imkonsiz", "Bo'lib-bo'lib tortish usuli", "Hammasini alohida tortish", "Bir marta tortish yetadi"],
    correctAnswer: "Bo'lib-bo'lib tortish usuli",
    explanation: "Klassik tarozi masalasi: 12 ni 3 guruhga bo'lib, 3 tortishda topish mumkin 😊",
  },
  {
    id: "29",
    level: 3,
    question: "Siz birinchi o'rindagi odamni quvib o'tsangiz, nechanchi bo'lasiz?",
    options: ["1-o'rin", "2-o'rin", "3-o'rin", "0-o'rin"],
    correctAnswer: "1-o'rin",
    explanation: "Birinchini quvib o'tsangiz, siz birinchi bo'lasiz 😊",
  },

  // Level 4 - Tezkor qaror / kulgili
  {
    id: "30",
    level: 4,
    question: "Bir shifokor sizga 3 dona dori beradi: har 30 daqiqada bittadan ichish kerak. Hammasini ichib bo'lish uchun qancha vaqt ketadi?",
    options: ["30 daqiqa", "60 daqiqa", "90 daqiqa", "120 daqiqa"],
    correctAnswer: "60 daqiqa",
    explanation: "1-dorini hoziroq ichasiz, 30 daq keyin 2-si, 60 daq keyin 3-si. Jami 60 daqiqa 😊",
  },
  {
    id: "31",
    level: 4,
    question: "Agar siz 'Men yolg'on gapiryapman' desangiz, bu gap rostmi yoki yolg'onmi?",
    options: ["Rost", "Yolg'on", "Ikkalasi ham", "Aniqlab bo'lmaydi"],
    correctAnswer: "Aniqlab bo'lmaydi",
    explanation: "Bu 'liar paradox' — mantiqiy paradoks 😄",
  },
  {
    id: "32",
    level: 4,
    question: "Qaysi narsa sizga tegishli, lekin boshqalar sizdan ko'proq ishlatadi?",
    options: ["Telefon", "Ism", "Uy", "Qalam"],
    correctAnswer: "Ism",
    explanation: "Ismingizni ko'proq boshqalar aytadi 😊",
  },
  {
    id: "33",
    level: 4,
    question: "Qaysi joyda daryo doim ikki marta kesib o'tiladi?",
    options: ["Ko'prikda", "Xaritada", "Tog'da", "Sahroda"],
    correctAnswer: "Xaritada",
    explanation: "Xaritada chiziqni istalgancha kesib o'tasiz 😄",
  },
  {
    id: "34",
    level: 4,
    question: "Bir odam 20 metr naridan ko'z bilan ko'radi, lekin 1 metr naridan ko'ra olmaydi. Nega?",
    options: ["Ko'zi og'riydi", "U ko'r", "U yaqinni ko'ra olmaydi (ko'zoynaksiz)", "U qorong'ida"],
    correctAnswer: "U yaqinni ko'ra olmaydi (ko'zoynaksiz)",
    explanation: "Bu yaqinni ko'rolmaslik (farsighted/near-sighted) holati 😄",
  },

  // Bonus - juda kulgili / chalg'ituvchi
  {
    id: "35",
    level: 2,
    question: "Qaysi savolga javob berishdan oldin doim o'ylab qolamiz?",
    options: ["Ismingiz nima?", "Necha yoshdasiz?", "Siz o'ylayapsizmi?", "Qayerdansiz?"],
    correctAnswer: "Siz o'ylayapsizmi?",
    explanation: "Bu savolning o'zi ham sizni o'ylantiradi 😄",
  },
  {
    id: "36",
    level: 3,
    question: "Qaysi narsani ko'z yumib ham ko'rish mumkin?",
    options: ["Tush", "Telefon", "Quyosh", "Dars"],
    correctAnswer: "Tush",
    explanation: "Tushni ko'z yumib ko'rasiz 😊",
  },
  {
    id: "37",
    level: 1,
    question: "Qaysi narsa suvga tushsa ham ho'l bo'lmaydi?",
    options: ["Tosh", "Baliq", "Soyabon", "Soya"],
    correctAnswer: "Soya",
    explanation: "Soya ho'l bo'lmaydi 😄",
  },
  {
    id: "38",
    level: 2,
    question: "Bir xona ichida 4 burchak bor. Har burchakda 1 ta mushuk o'tirgan. Har mushuk oldida 3 ta mushuk bo'lsa, jami nechta mushuk?",
    options: ["4", "8", "12", "16"],
    correctAnswer: "4",
    explanation: "Har mushuk oldida qolgan 3 mushuk ko'rinadi. Jami 4 mushuk 😊",
  },
  {
    id: "39",
    level: 3,
    question: "1 dan 10 gacha bo'lgan raqamlar ichida qaysi biri eng ko'p harf bilan yoziladi?",
    options: ["Bir", "To'rt", "Sakkiz", "Yetti"],
    correctAnswer: "Sakkiz",
    explanation: "O'zbekchada 'sakkiz' ko'proq harfga ega 😄",
  },
  {
    id: "40",
    level: 4,
    question: "Bir ota o'g'liga: 'Men sening yoshingda bo'lganimda, sen mendan 2 marta kichik eding' dedi. Hozir ota 40 yosh bo'lsa, o'g'il necha yosh?",
    options: ["10", "15", "20", "25"],
    correctAnswer: "20",
    explanation: "Ota 20 yosh bo'lganda o'g'il 10 yosh (2 marta kichik). Farq 20. Ota 40 → o'g'il 20 😊",
  },
  {
    id: "41",
    level: 2,
    question: "Qaysi narsani sindirsangiz ham, u ishlashda davom etadi?",
    options: ["Telefon", "O'yinchoq", "Yurak", "Tuxum"],
    correctAnswer: "Yurak",
    explanation: "Hazil: yurak 'sinishi' mumkin, lekin baribir uradi 😄",
  },
  {
    id: "42",
    level: 3,
    question: "Qaysi joyda '1+1=11' bo'lishi mumkin?",
    options: ["Matematika", "Ikki sonli tizim (binary)", "Kalkulyator", "Daftarda"],
    correctAnswer: "Ikki sonli tizim (binary)",
    explanation: "Binary’da 1+1=10 bo'ladi, lekin bu savol chalg'ituvchi 😄 (xohlasang, buni tuzatib aniq variant qilaman)",
  },
  {
    id: "43",
    level: 1,
    question: "Nimani ko'rmasdan ham aytish mumkin?",
    options: ["Ha", "Rang", "Uy", "Daraxt"],
    correctAnswer: "Ha",
    explanation: "Ko'rmasdan ham 'ha' deyish mumkin 😊",
  },
  {
    id: "44",
    level: 4,
    question: "Agar siz 3 ta olmani olib, 2 tasini yeb qo'ysangiz, sizda nechta olma qoladi?",
    options: ["1", "2", "3", "0"],
    correctAnswer: "3",
    explanation: "Siz olgan olmalar sizniki bo'lib qoladi, yeganingiz ham 'sizda' bo'lgan edi 😄",
  },
  {
    id: "45",
    level: 2,
    question: "Qaysi narsa doim ko'tariladi, lekin hech qachon tushmaydi?",
    options: ["Yosh", "Narx", "Quyosh", "Shamol"],
    correctAnswer: "Yosh",
    explanation: "Yosh doim oshadi 😊",
  },
];
