import type { Question } from "./Millionaire";

export const QUESTION_BANK: Question[] = [
  {
    id: "e1",
    difficulty: "easy",
    category: "Vocabulary",
    text: "'Apple' so'zi nimani anglatadi?",
    options: { A: "Olma", B: "Banan", C: "Uzum", D: "Shaftoli" },
    correct: "A",
  },
  {
    id: "e2",
    difficulty: "easy",
    category: "Daily",
    text: "'Morning' qaysi vaqt?",
    options: { A: "Kechasi", B: "Tushdan keyin", C: "Ertalab", D: "Kechqurun" },
    correct: "C",
  },
  {
    id: "e3",
    difficulty: "easy",
    category: "Grammar",
    text: "I ___ a student.",
    options: { A: "am", B: "is", C: "are", D: "be" },
    correct: "A",
  },
  {
    id: "e4",
    difficulty: "easy",
    category: "Colors",
    text: "Qora rangni ingliz tilida qanday aytiladi?",
    options: { A: "Red", B: "Blue", C: "Black", D: "White" },
    correct: "C",
  },
  {
    id: "e5",
    difficulty: "easy",
    category: "Numbers",
    text: "5 + 3 = ?",
    options: { A: "7", B: "8", C: "9", D: "10" },
    correct: "B",
  },
  {
    id: "m1",
    difficulty: "medium",
    category: "Grammar",
    text: "He ___ to school every day.",
    options: { A: "go", B: "goes", C: "going", D: "gone" },
    correct: "B",
  },
  {
    id: "m2",
    difficulty: "medium",
    category: "Vocabulary",
    text: "'Big' so'zining sinonimi qaysi?",
    options: { A: "Small", B: "Large", C: "Cold", D: "Slow" },
    correct: "B",
  },
  {
    id: "m3",
    difficulty: "medium",
    category: "Grammar",
    text: "Choose the correct: 'I ___ finished my homework.'",
    options: { A: "has", B: "have", C: "having", D: "had been" },
    correct: "B",
  },
  {
    id: "m4",
    difficulty: "medium",
    category: "History",
    text: "O'zbekiston poytaxti qaysi shahar?",
    options: { A: "Samarqand", B: "Buxoro", C: "Toshkent", D: "Xiva" },
    correct: "C",
  },
  {
    id: "m5",
    difficulty: "medium",
    category: "Science",
    text: "Quyoshga eng yaqin sayyora qaysi?",
    options: { A: "Venera", B: "Merkuriy", C: "Mars", D: "Yer" },
    correct: "B",
  },
  {
    id: "h1",
    difficulty: "hard",
    category: "Grammar",
    text: "If I ___ time, I would help you.",
    options: { A: "have", B: "had", C: "will have", D: "has" },
    correct: "B",
  },
  {
    id: "h2",
    difficulty: "hard",
    category: "Vocabulary",
    text: "'Reliable' so'zi eng yaqin ma'nosi?",
    options: { A: "Ishonchli", B: "Zararli", C: "Kuchsiz", D: "Arzon" },
    correct: "A",
  },
  {
    id: "h3",
    difficulty: "hard",
    category: "Reading",
    text: "Which is closest to 'However'?",
    options: { A: "Because", B: "Therefore", C: "But", D: "And" },
    correct: "C",
  },
  {
    id: "h4",
    difficulty: "hard",
    category: "Literature",
    text: "Amir Temur qaysi yillar oralig'ida hukm qilgan?",
    options: { A: "1326-1405", B: "1336-1405", C: "1346-1405", D: "1356-1405" },
    correct: "B",
  },
  {
    id: "h5",
    difficulty: "hard",
    category: "Science",
    text: "Kislorodning kimyoviy formulasi?",
    options: { A: "O2", B: "O3", C: "O", D: "O4" },
    correct: "A",
  },
  {
    id: "x1",
    difficulty: "expert",
    category: "Grammar",
    text: "Hard: 'By the time he arrived, we ___.'",
    options: { A: "left", B: "have left", C: "had left", D: "leave" },
    correct: "C",
  },
  {
    id: "x2",
    difficulty: "expert",
    category: "Vocabulary",
    text: "'Scarce' so'zining ma'nosi?",
    options: { A: "Ko'p", B: "Kam / tanqis", C: "Tez", D: "Yangi" },
    correct: "B",
  },
  {
    id: "x3",
    difficulty: "expert",
    category: "Philosophy",
    text: "'Cogito ergo sum' degan faylasuf kim?",
    options: { A: "Aristotel", B: "Platon", C: "Dekart", D: "Kant" },
    correct: "C",
  },
  {
    id: "x4",
    difficulty: "expert",
    category: "Mathematics",
    text: "Integral hisobini ixtiro qilgan olim?",
    options: { A: "Newton", B: "Leybnits", C: "Eyler", D: "Gauss" },
    correct: "B",
  },
  {
    id: "x5",
    difficulty: "expert",
    category: "History",
    text: "Birinchi jahon urushi qachon tugagan?",
    options: { A: "1917", B: "1918", C: "1919", D: "1920" },
    correct: "B",
  },
];